def cleaning_ads(new):
    news = new
    news.remove('Подписка')
    news.remove('отключает')
    news.remove('баннерную')
    news.remove('рекламу')
    news.remove('на')
    news.remove('сайтах')
    news.remove('РБК')
    news.remove('и')
    news.remove('обеспечивает')
    news.remove('его')
    news.remove('корректную')
    news.remove('работу')
    news.remove('Всего')
    news.remove('99₽')
    news.remove('в')
    news.remove('месяц')
    news.remove('для')
    news.remove('3-х')
    news.remove('устройств')
    news.remove('Продлевается')
    news.remove('автоматически')
    news.remove('каждый')
    news.remove('месяц,')
    news.remove('но')
    news.remove('вы')
    news.remove('всегда')
    news.remove('сможете')
    news.remove('отписаться')
    return news